remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Implementation and Evaluation of Virtual Reality Telepresence in 5.7K 360-degree Video with head-foveated rendering and MEC-Assisted Millimeter-Wave 5G Communication
description: [A short description of your site's purpose]
